openapi: 3.0.0
tags:
  - name: Booking
    description: Управление бронированиями
  - name: Message
    description: Отправка и загрузка сообщений
  - name: Place
    description: Управление площадками для мероприятий
info:
  title: Сервис бронирований
  version: '0.2'
  description: |-
    Данный сервис предназначен для работы с бронированиями: создания, удаления и изменения их состояний.
    Связанный проект Confluence: https://snowbro.atlassian.net/wiki/spaces/SBAHWC/overview
  contact:
    name: Александр Сафонов
    email: snowborodist@gmail.com
servers:
  - url: 'https://localhost:3000'
    description: Develop
paths:
  '/booking/{identifier}':
    parameters:
      - schema:
          type: string
        name: identifier
        in: path
        required: true
        description: Уникальный идентификатор бронирования
    get:
      summary: Получение информации о бронировании
      tags:
        - Booking
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Booking'
              examples:
                John's Pizza Example:
                  value:
                    bookingIdentifier: 409d0818-73bf-4a1f-a23b-81505778c663
                    organizerIdentifier: a5f95893-353b-4118-8ab7-46f406fc382c
                    place:
                      identifier: 596e65fd-141f-4295-824a-09f2f24f9cc8
                      photo:
                        - 'https://alterainvest.ru/upload/iblock/aa6/aa6c3905844c71e819fc5a4214f4d238.jpg'
                        - 'https://writegate.ru/wp-content/uploads/2019/07/restoran-ruski.jpg'
                        - 'https://i.timeout.ru/pix/531719.jpeg'
                      name: John's Pizza House
                      description: Simply the best place to conduct an Italian-style party in New York!
                      ratingValue: 4.9
                      price: 10000
                      bookingInterval: 1
                      owner:
                        identifier: b6f192f3-f0e3-4780-8e74-b18834343630
                        name: John Cheeser
                        contact:
                          - 'phone:+79629860431'
                          - 'email:johns_place@gmail.com'
                      openBookingIntervals:
                        - startDate: '2021-04-01 00:00:00.000'
                          duration: '72'
                        - startDate: '2021-04-10 00:00:00.000'
                          duration: '48'
        '404':
          description: Booking Not Found
      operationId: get-booking-identifier
      description: 'Возвращает объект, содержащий информацию о бронировании.'
      security:
        - OAuth2: []
      x-internal: false
      parameters: []
    delete:
      summary: Удаление бронирования
      operationId: delete-booking-identifier
      responses:
        '200':
          description: OK
        '404':
          description: Booking Not Found
      description: Для удаления необходимо указать уникальный идентификатор бронирования.
      security:
        - OAuth2: []
      parameters: []
      tags:
        - Booking
  /booking:
    post:
      summary: Добавление нового бронирования
      operationId: post-booking
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Booking'
              examples:
                John's Pizza Example:
                  value:
                    bookingIdentifier: 409d0818-73bf-4a1f-a23b-81505778c663
                    organizerIdentifier: a5f95893-353b-4118-8ab7-46f406fc382c
                    place:
                      identifier: 596e65fd-141f-4295-824a-09f2f24f9cc8
                      photo:
                        - 'https://alterainvest.ru/upload/iblock/aa6/aa6c3905844c71e819fc5a4214f4d238.jpg'
                        - 'https://writegate.ru/wp-content/uploads/2019/07/restoran-ruski.jpg'
                        - 'https://i.timeout.ru/pix/531719.jpeg'
                      name: John's Pizza House
                      description: Simply the best place to conduct an Italian-style party in New York!
                      ratingValue: 4.9
                      price: 10000
                      bookingInterval: 1
                      owner:
                        identifier: b6f192f3-f0e3-4780-8e74-b18834343630
                        name: John Cheeser
                        contact:
                          - 'phone:+79629860431'
                          - 'email:johns_place@gmail.com'
                      openBookingIntervals:
                        - startDate: '2021-04-01 00:00:00.000'
                          duration: '72'
                        - startDate: '2021-04-10 00:00:00.000'
                          duration: '48'
        '500':
          description: Internal Server Error
      description: 'При успешном выполнении запроса в теле ответа возвращается объект, содержащий информацию о созданном бронировании.'
      security:
        - OAuth2: []
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              properties:
                placeIdentifier:
                  type: string
                  minLength: 1
                  format: uuid
                organizerIdentifier:
                  type: string
                  minLength: 1
                  format: uuid
              required:
                - placeIdentifier
                - organizerIdentifier
            examples:
              example:
                value:
                  placeIdentifier: 04f06287-724f-480e-a49c-4421ff95f6e8
                  organizerIdentifier: 1de2418c-a6ac-4fc0-9a2d-c7d175e9073d
        description: 'Для создания нового бронирования необходимо передать в теле запроса уникальные идентификаторы бронируемой площадки и организатора мероприятий, который осуществляет бронирование'
      tags:
        - Booking
  '/booking/{identifier}/state':
    parameters:
      - schema:
          type: string
        name: identifier
        in: path
        required: true
        description: Уникальный идентификатор бронирования
    get:
      summary: Получение состояния бронирования
      tags:
        - Booking
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookingState'
              examples:
                Example:
                  value:
                    bookingIdentifier: 409d0818-73bf-4a1f-a23b-81505778c663
                    startDate: '2021-04-01 16:00:00.000'
                    duration: 48
                    totalPrice: 26000
                    additionalServices:
                      - identifier: a5f95893-353b-4118-8ab7-46f406fc382c
                        photo:
                          - 'https://www.meme-arsenal.com/memes/77cbef6b195b7b35f146f17df723339b.jpg'
                          - 'http://i.mycdn.me/i?r=AzEPZsRbOZEKgBhR0XGMT1RkNaYdgCNXPZqLheIqtYIYTqaKTM5SRkZCeTgDn6uOyic'
                          - 'https://a.d-cd.net/941es-960.jpg'
                        name: DJ
                        description: Good DJ for your party!
                        totalPrice: 2000
                        isChosen: true
                      - identifier: 596e65fd-141f-4295-824a-09f2f24f9cc8
                        photo:
                          - 'https://f11.pmo.ee/MmOaZrzTIrzK4YV2lDhpNwC7GBk=/1370x820/smart/nginx/o/2016/11/09/6055121t1hd5a2.jpg'
                          - 'https://img.novosti-n.org/upload/ukraine/824889.jpg'
                        name: Catering
                        description: Wish any dish for your mega-party
                        totalPrice: 4000
                        isChosen: false
        '404':
          description: Booking Not Found
          content:
            application/json:
              schema:
                type: object
                properties: {}
      operationId: get-booking-identifier-state
      description: 'Возвращает объект, содержащий состояние бронирования.'
      security:
        - OAuth2: []
    put:
      summary: Обновление интервалов бронирования
      operationId: put-booking-identifier-state
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookingState'
              examples:
                Example:
                  value:
                    bookingIdentifier: 409d0818-73bf-4a1f-a23b-81505778c663
                    startDate: '2021-04-01 16:00:00.000'
                    duration: 48
                    totalPrice: 26000
                    additionalServices:
                      - identifier: a5f95893-353b-4118-8ab7-46f406fc382c
                        photo:
                          - 'https://www.meme-arsenal.com/memes/77cbef6b195b7b35f146f17df723339b.jpg'
                          - 'http://i.mycdn.me/i?r=AzEPZsRbOZEKgBhR0XGMT1RkNaYdgCNXPZqLheIqtYIYTqaKTM5SRkZCeTgDn6uOyic'
                          - 'https://a.d-cd.net/941es-960.jpg'
                        name: DJ
                        description: Good DJ for your party!
                        totalPrice: 2000
                        isChosen: true
                      - identifier: 596e65fd-141f-4295-824a-09f2f24f9cc8
                        photo:
                          - 'https://f11.pmo.ee/MmOaZrzTIrzK4YV2lDhpNwC7GBk=/1370x820/smart/nginx/o/2016/11/09/6055121t1hd5a2.jpg'
                          - 'https://img.novosti-n.org/upload/ukraine/824889.jpg'
                        name: Catering
                        description: Wish any dish for your mega-party
                        totalPrice: 4000
                        isChosen: false
        '500':
          description: Internal Server Error
      description: 'При успешном выполнении запроса возвращает объект, содержащий новое состояние бронирования.'
      security:
        - OAuth2: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                startDate:
                  type: string
                  format: date-time
                duration:
                  type: integer
                  minimum: 0
                  description: ' Длительность интервала бронирования в часах'
              required:
                - startDate
                - duration
            examples:
              Example:
                value:
                  startDate: '2021-04-01 16:00:00.000'
                  duration: 48
          application/xml:
            schema:
              type: object
              properties: {}
          multipart/form-data:
            schema:
              type: object
              properties: {}
          text/html:
            schema:
              type: object
              properties: {}
        description: ''
      tags:
        - Booking
  '/place/{identifier}/reviews':
    parameters:
      - schema:
          type: string
        name: identifier
        in: path
        required: true
        description: Уникальный идентификатор площадки для мероприятий
    get:
      summary: Получение отзывов к площадке
      tags:
        - Place
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReviewsPage'
              examples:
                Example:
                  value:
                    reviews:
                      - identifier: c1d7bf27-26ec-43d4-a6bf-e637203c1e9c
                        author: Алексей Петров
                        dateCreated: '2019-08-24T14:15:22Z'
                        reviewBody: 'Место очень понравилось: было весело и очень вкусно!'
                      - identifier: cc8f7e5a-30a3-4977-86ac-9a685b025ad1
                        author: Ульяна Иванова
                        dateCreated: '2019-08-24T17:03:22Z'
                        reviewBody: 'Место так себе, не особо понравилось: было скучно и еду принесли холодную!'
                    page: 1
                    pagesCount: 10
        '400':
          description: Invalid Page Value
        '404':
          description: Place Not Found
      operationId: get-place-identifier-reviews
      description: 'Возвращает объект, содержащий страницу списка отзывов к площадке для мероприятий.'
      parameters:
        - schema:
            type: integer
            default: '1'
          in: query
          name: page
          description: ' Номер страницы списка отзывов'
          required: true
      security:
        - OAuth2: []
  '/booking/{identifier}/service':
    parameters:
      - schema:
          type: string
        name: identifier
        in: path
        required: true
        description: Уникальный идентификатор бронирования
    post:
      summary: Добавить услугу к бронированию
      operationId: post-booking-identifier-service
      responses:
        '201':
          description: Service Added To Booking
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookingState'
              examples:
                Example:
                  value:
                    bookingIdentifier: 409d0818-73bf-4a1f-a23b-81505778c663
                    startDate: '2019-08-24T17:03:22Z'
                    duration: 48
                    totalPrice: 26000
                    additionalServices:
                      - identifier: a5f95893-353b-4118-8ab7-46f406fc382c
                        photo:
                          - 'https://www.meme-arsenal.com/memes/77cbef6b195b7b35f146f17df723339b.jpg'
                          - 'http://i.mycdn.me/i?r=AzEPZsRbOZEKgBhR0XGMT1RkNaYdgCNXPZqLheIqtYIYTqaKTM5SRkZCeTgDn6uOyic'
                          - 'https://a.d-cd.net/941es-960.jpg'
                        name: DJ
                        description: Good DJ for your party!
                        totalPrice: 2000
                        isChosen: true
                      - identifier: 596e65fd-141f-4295-824a-09f2f24f9cc8
                        photo:
                          - 'https://f11.pmo.ee/MmOaZrzTIrzK4YV2lDhpNwC7GBk=/1370x820/smart/nginx/o/2016/11/09/6055121t1hd5a2.jpg'
                          - 'https://img.novosti-n.org/upload/ukraine/824889.jpg'
                        name: Catering
                        description: Wish any dish for your mega-party
                        totalPrice: 4000
                        isChosen: false
        '404':
          description: Booking Not Found
        '500':
          description: Internal Server Error
      tags:
        - Booking
      security:
        - OAuth2: []
      parameters:
        - schema:
            type: string
          in: header
          name: additionalServiceIdentifier
          description: Уникальный идентификатор добавляемой дополнительной услуги
          required: true
      description: 'При успешном выполнении запроса в теле ответа возвращается объект, содержащий новое состояние бронирования.'
    delete:
      summary: Убрать дополнительную услугу из бронирования
      operationId: delete-booking-identifier-service
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookingState'
              examples:
                Example:
                  value:
                    bookingIdentifier: 409d0818-73bf-4a1f-a23b-81505778c663
                    startDate: '2019-08-24T17:03:22Z'
                    duration: 48
                    totalPrice: 26000
                    additionalServices:
                      - identifier: a5f95893-353b-4118-8ab7-46f406fc382c
                        photo:
                          - 'https://www.meme-arsenal.com/memes/77cbef6b195b7b35f146f17df723339b.jpg'
                          - 'http://i.mycdn.me/i?r=AzEPZsRbOZEKgBhR0XGMT1RkNaYdgCNXPZqLheIqtYIYTqaKTM5SRkZCeTgDn6uOyic'
                          - 'https://a.d-cd.net/941es-960.jpg'
                        name: DJ
                        description: Good DJ for your party!
                        totalPrice: 2000
                        isChosen: true
                      - identifier: 596e65fd-141f-4295-824a-09f2f24f9cc8
                        photo:
                          - 'https://f11.pmo.ee/MmOaZrzTIrzK4YV2lDhpNwC7GBk=/1370x820/smart/nginx/o/2016/11/09/6055121t1hd5a2.jpg'
                          - 'https://img.novosti-n.org/upload/ukraine/824889.jpg'
                        name: Catering
                        description: Wish any dish for your mega-party
                        totalPrice: 4000
                        isChosen: false
        '404':
          description: Booking Not Found
        '500':
          description: Internal Server Error
      tags:
        - Booking
      parameters:
        - schema:
            type: string
          in: header
          name: additionalServiceIdentifier
          description: Уникальный идентификатор убираемой из бронирования услуги
          required: true
      security:
        - OAuth2: []
      description: 'При успешном выполнении запроса в теле ответа возвращается объект, содержащий новое состояние бронирования.'
  '/booking/{identifier}/commit':
    parameters:
      - schema:
          type: string
        name: identifier
        in: path
        required: true
        description: Уникальный идентификатор бронирования
    post:
      summary: Подтвердить бронирование
      operationId: post-booking-identifier-commit
      responses:
        '200':
          description: OK
        '304':
          description: Booking Already Commited
        '404':
          description: Booking Not Found
      description: 'Запрос позволяет пользователю подтвердить бронирование. Если бронирование уже было подтверждено, то будет возвращен код ответа 304.'
      security:
        - OAuth2: []
      tags:
        - Booking
  /message:
    post:
      summary: Отправить сообщение
      operationId: post-message
      responses:
        '200':
          description: OK
        '404':
          description: User Not Found
      tags:
        - Message
      description: Запрос позволяет пользователю отправить сообщение через сервис.
      security:
        - OAuth2: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                senderIdentifier:
                  type: string
                  format: uuid
                receiverIdentifier:
                  type: string
                  format: uuid
                messageText:
                  type: string
                  minLength: 1
              required:
                - senderIdentifier
                - receiverIdentifier
                - messageText
            examples:
              Example:
                value:
                  senderIdentifier: 97240fea-f7e3-4718-9337-39e295de9679
                  receiverIdentifier: 76c1e427-3520-4cb3-a10d-a88c2fbc0cad
                  messageText: 'Привет, как дела?'
components:
  schemas:
    Booking:
      description: Информация о бронировании.
      type: object
      properties:
        bookingIdentifier:
          type: string
          format: uuid
        organizerIdentifier:
          type: string
          format: uuid
        place:
          type: object
          description: Бронируемая площадка
          required:
            - identifier
            - name
            - description
            - ratingValue
            - price
            - bookingInterval
            - owner
            - openBookingIntervals
          properties:
            identifier:
              type: string
              format: uuid
            photo:
              type: array
              uniqueItems: true
              items:
                type: string
                format: uri
            name:
              type: string
              minLength: 1
              maxLength: 100
            description:
              type: string
            ratingValue:
              type: number
              minimum: 1
              maximum: 5
              format: float
            price:
              type: number
              minimum: 0
              format: float
            bookingInterval:
              type: number
              enum:
                - 0
                - 1
                - 2
              description: 'Тип интервала бронирования, может принимать одно из следующих значений: 0 - разовый платеж, 1 - день, 2 - час'
            owner:
              type: object
              description: Владелец бронируемой площадки
              required:
                - identifier
                - name
                - contact
              properties:
                identifier:
                  type: string
                name:
                  type: string
                  minLength: 1
                  maxLength: 92
                contact:
                  type: array
                  description: |-
                    Массив текстовых представлений контактов:
                    <тип_контакта>:<значение_контакта>
                  items:
                    type: string
                    maxLength: 100
            openBookingIntervals:
              type: array
              uniqueItems: true
              minItems: 1
              description: Список открытых интервалов бронирования
              items:
                type: object
                properties:
                  startDate:
                    type: string
                    format: date-time
                  duration:
                    type: integer
                    minimum: 1
                    description: ' Длительность доступного для бронирования интервала, задается как количество часов'
                required:
                  - startDate
                  - duration
      required:
        - bookingIdentifier
        - organizerIdentifier
        - place
      title: Booking
    BookingState:
      description: Состояние бронирования.
      type: object
      properties:
        bookingIdentifier:
          type: string
          format: uuid
        startDate:
          type: string
          format: date-time
        duration:
          type: integer
          minimum: 0
          description: Длительность бронирования в часах
        totalPrice:
          type: number
          minimum: 0
          format: float
        additionalServices:
          type: array
          uniqueItems: true
          description: Массив доступных для бронирования дополнительных услуг
          items:
            type: object
            properties:
              identifier:
                type: string
                minLength: 1
              photo:
                type: array
                uniqueItems: true
                items:
                  type: string
                  format: uri
              name:
                type: string
                minLength: 1
                maxLength: 100
              description:
                type: string
              totalPrice:
                type: number
                minimum: 0
                format: float
              isChosen:
                type: boolean
                default: false
                description: 'Флаг, показывающий, выбрана ли услуга в текущем бронировании'
            required:
              - identifier
              - name
              - description
              - totalPrice
              - isChosen
      required:
        - bookingIdentifier
        - startDate
        - duration
        - totalPrice
        - additionalServices
      title: BookingState
    ReviewsPage:
      description: 'Страница списка отзывов к площадке для бронирования. Список выводится постранично, по 10 отзывов на странице.'
      type: object
      properties:
        reviews:
          type: array
          uniqueItems: true
          minItems: 0
          description: Отзыв к площадке
          items:
            type: object
            description: Отзыв к площадке для бронирования
            properties:
              identifier:
                type: string
                format: uuid
              author:
                type: string
                minLength: 1
              dateCreated:
                type: string
                format: date-time
              reviewBody:
                type: string
                minLength: 1
            required:
              - identifier
              - author
              - dateCreated
              - reviewBody
        page:
          type: integer
          description: Текущий номер страницы списка отзывов
        pagesCount:
          type: integer
          minimum: 0
          description: Общее число страниц в списке отзывов
      required:
        - reviews
        - page
        - pagesVount
      title: ReviewsPage
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: ''
          refreshUrl: ''
          scopes: {}
